name: cil_twitter
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pytorchx
  - numpy
  - pandas
  - scikit-learn
  - pip
  - pip:
    - keras
    - torch
    - transformers
    - wordsegment
    - tqdm
    